title: <p align="center"> Gunavardhani Yalavarthi </p>
logo:  /assets/img/logo.png
     
description:
  <p align="center">
  <a href="https://www.linkedin.com/in/gunavardhani-yalavarthi-776232200/">LinkedIn</a> |
  <a href="https://github.com/guna981">GitHub</a>
  
  <br>   
  I'm working as automation developer using REST API and programming languages. Currently learning about Machine learning and Artificial Intelligence.
  <br>
  </p>






theme: jekyll-theme-minimal
